### ISSUE TITLE
Recipe missing for clear Glass Button Light

### ISSUE THREAD

**Issue by zauberparacelsus** [kreezxil/Lever-Button-Lights#1]
The recipe for the clear/unstained Glass Button Light appears to be missing, so the item is effectively unobtainable without creative mode or NEI.

**Comment by kreezxil** [comment]
which version of the mod are you using?

**Comment by zauberparacelsus** [comment]
I'm using version 1.12.2-3.2.9, with forge version 14.23.5.2847

**Comment by kreezxil** [comment]
thank you, i've got a pack to update and then I'll get a fix out for that
after I test and verify.

Forgot to ask you what pack you were using?

**Comment by zauberparacelsus** [comment]
It's a custom one, actually.

**Comment by kreezxil** [comment]
fixed in 3.3.0
