### ISSUE TITLE
Button hitboxes are comically oversized

### ISSUE THREAD

**Issue by DoomRater** [kreezxil/Lever-Button-Lights#2]
They look like lever hitboxes, but buttons are WAY smaller.
![2020-04-03_22 06 40](https://user-images.githubusercontent.com/4010432/78416559-721b8700-75f7-11ea-9213-95c8c4167374.png)
![2020-04-03_22 07 26](https://user-images.githubusercontent.com/4010432/78416569-8495c080-75f7-11ea-9d8c-bdb3c3552c83.png)

**Comment by kreezxil** [comment]
that's because they are levers with button textures. I don't have have
enough skill to fix the hitboxes tho.

**Comment by DoomRater** [comment]
Oh wow every time I thought I understood what to do to fix it I hit a roadblock.  I'm resorting to overriding the bounding box logic in ColoredButtonLights.java using some chimera of the code out of the lever and button java classes, but that seems to get the results I expected.

**Comment by kreezxil** [comment]
I ran into these issues too.

Thanks for giving it a shot, are you registered on https://curseforge.com? I can add you as a contributor once you submit a pr. Also are you registered in the reward system too?

**Comment by DoomRater** [comment]
I am actually!  Username is the same over there.

Edit: Reward system?  I'm unfamliar with that.

**Comment by kreezxil** [comment]
Nice. i'll cut you in for 10% of my take on this for fixing the models after the pr.

**Comment by DoomRater** [comment]
Aha, now I see why they're different- I was informed levers can be rotated on the floor while buttons cannot (normally).  Your buttons can and I didn't account for that and don't have bounding boxes for rotated buttons.  That leads to this:
![2020-04-04_14 21 49](https://user-images.githubusercontent.com/4010432/78458478-a5a1f400-767f-11ea-9f72-7744bed5163f.png)
So it's closer to fixed, but not for rotated buttons on the ground.

**Comment by DoomRater** [comment]
Updated my PR with the extra logic for rotated buttons on the floor.

**Comment by kreezxil** [comment]
You're not in the curserewards program btw
![image](https://user-images.githubusercontent.com/3880072/78459273-7a1e0a00-767d-11ea-94ee-fa190015e2ef.png)
https://authors.curseforge.com/knowledge-base/rewards/3448-how-to-join-and-redeem-rewards

**Comment by DoomRater** [comment]
"Tax info" Looks like I have some research to do before I sign up then as I'm on disability and need to know how that will affect any benefits I get before I do.

**Comment by kreezxil** [comment]
you won't make much, however it could easily be $20 a quarter tho

**Comment by kreezxil** [comment]
You would need about 100 projects like I have to avg about $75/month USD

**Comment by kreezxil** [comment]
or a really popular mod like Iron Chests which is grossing it's current author nearly $2000/month USD provided they're in the program.
